### PR TITLE
Include extra file for icinga check definitions

### PR DESCRIPTION
**Pull request by dc-mattj**

### CODE REVIEW

**Comment by yankcrime** [comment]
:+1:

**Comment by spjmurray** [comment]
Ah yes, all DHCP servers need to be hard coded to be aware of the existence of icinga... begrudging :+1:  unless you'd rather add in an 'includes' parameter and add a generic list to the template file.  Actually why the hell does icinga need dhcp integration?  Is omapi not good enough?

**Comment by dc-mattj** [comment]
Yes, you're probably right about making it more generic. Will change. It needs integration because since the slave doesn't provide dynamic ranges anymore, it needs to have a specific fake entry to respond to.

**Comment by spjmurray** [comment]
:+1: Can make it conditional as an when we need to

**Pull request merged**
